### ISSUE TITLE
REST API adapters

### ISSUE THREAD

**Issue by artemiusgreat** [nautechsystems/Nautilus#18]
Hi. Thank you for sharing your work. I was wondering, this framework is deeply integrated with FIX and sockets. **Is there a sample or some guidelines regarding the recommended way to implement REST API adapters.** For example, for stockbrokers like Alpaca Markets, Tradier, Interactive Brokers, or TD Ameritrade? 

I see that it requires to implement IDataGateway and ITradingGateway, but still trying to understand if I actually need to use sockets, data bus, and message bus, or it would be enough to call data repository or gateway directly?

**Comment by cjdsellers** [comment]
I just saw this, I'll write a detailed response soon. Cheers.

**Comment by cjdsellers** [comment]
It depends on your individual use case. The codebase is more of a framework along with some example applications for FIX4.4 connections. If you wanted to implement your own REST API adapters for `Data` and `Execution` services then yes you would need to implement both the IDataGateway and ITradingGateway. 

I recommend you have a look through the code in the NautilusData and NautilusExecutor projects. You'd need to modify the config.json and how its parsed, as well as the factories to build the services, along with the adapter for the broker itself.

Was there a particular broker you wanted to integrate with?

There are current plans to write Interactive Brokers, Binance and BitMEX adapters.

**Comment by cjdsellers** [comment]
Closed for now as the direction for this repository has changed.
